spring:
  application:
    name: producer-kafka
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:29092}
    producer:
      properties:
        topic: news.json
        num-partitions: 5

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: cloudkarafka
  kafka:
    bootstrap-servers: ${KAFKA_URL:ark-01.srvs.cloudkafka.com:9094, ark-02.srvs.cloudkafka.com:9094, ark-03.srvs.cloudkafka.com:9094}
    producer:
      properties:
        topic: ${CLOUDKARAFKA_USERNAME}-news.json
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-256
        jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
