spring:
  application:
    name: consumer-cloud-stream
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URL:localhost:29092}
          min-partition-count: 5
      bindings:
        news-in-0:
          destination: news.json
          content-type: application/json
          group: consumerCloudStreamGroup
          consumer:
            start-offset: latest
            concurrency: 2

management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate.on-profile: cloudkarafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URL:ark-01.srvs.cloudkafka.com:9094, ark-02.srvs.cloudkafka.com:9094, ark-03.srvs.cloudkafka.com:9094}
          auto-create-topics: false
          configuration:
            security:
              protocol: SASL_SSL
            sasl:
              mechanism: SCRAM-SHA-256
              jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${CLOUDKARAFKA_USERNAME}" password="${CLOUDKARAFKA_PASSWORD}";
      bindings:
        news-in-0:
          destination: ${CLOUDKARAFKA_USERNAME}-news.json
